Repository AY2425S1-CS2103T-W09-3/tp, pull requests merged in 2024-10, with the labels that each got.

#40 Update index and readme
  README.md
  docs/index.md
Labels: type.Task

#52 Modify existing models
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
Labels: priority.High

#51 Add small increments for load feature
  docs/AboutUs.md
  docs/images/choaticman 2.jpg
  docs/team/choaticman 2.md
  src/main/java/seedu/address/model/ReadOnlyHireMe.java
  src/main/java/seedu/address/storage/HireMeStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
Labels: priority.High

#46 Modify delete command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: priority.High

#49 Add interfaces for hireMe storage save feature
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyHireMe.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/HireMeStorage.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.High

#61 Modify delete command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High

#63 Modify clear and exit commands
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
Labels: priority.High

#69 Update test cases
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/internshipapplication/Name.java
  src/main/java/seedu/address/model/internshipapplication/Role.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/internshipapplication/PersonTest.java
  src/test/java/seedu/address/model/internshipapplication/UniqueListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/InternshipApplicationBuilder.java
  src/test/java/seedu/address/testutil/InternshipApplicationUtil.java
  src/test/java/seedu/address/testutil/TypicalInternshipApplications.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#73 Update test cases for commands package
  src/main/java/seedu/address/logic/validator/NameValidator.java
  src/main/java/seedu/address/logic/validator/RoleValidator.java
  src/main/java/seedu/address/model/internshipapplication/Date.java
  src/main/java/seedu/address/model/internshipapplication/Role.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/testutil/TypicalInternshipApplications.java
Labels: priority.High

#75 Update test cases for storage
  src/main/java/seedu/address/logic/validator/DateValidator.java
  src/main/java/seedu/address/logic/validator/EmailValidator.java
  src/main/java/seedu/address/logic/validator/NameValidator.java
  src/main/java/seedu/address/logic/validator/RoleValidator.java
  src/main/java/seedu/address/storage/JsonAdaptedInternship.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidInternshipAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidInternshipAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalInternshipsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalInternshipApplications.java
Labels: priority.High

#77 Fix models test cases
  src/main/java/seedu/address/logic/validator/NameValidator.java
  src/main/java/seedu/address/model/internshipapplication/Company.java
  src/main/java/seedu/address/model/internshipapplication/Date.java
  src/main/java/seedu/address/model/internshipapplication/Email.java
  src/main/java/seedu/address/model/internshipapplication/InternshipApplication.java
  src/main/java/seedu/address/model/internshipapplication/Name.java
  src/main/java/seedu/address/model/internshipapplication/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/internshipapplication/Role.java
  src/main/java/seedu/address/model/internshipapplication/UniqueList.java
  src/main/java/seedu/address/model/internshipapplication/exceptions/DuplicateInternshipException.java
  src/main/java/seedu/address/model/internshipapplication/exceptions/DuplicatePersonException.java
  src/main/java/seedu/address/model/internshipapplication/exceptions/PersonNotFoundException.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/internshipapplication/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/internshipapplication/UniqueListTest.java
Labels: priority.High

#82 Fix failing managers test cases
  src/main/java/seedu/address/model/AddressBook.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Bug

#84 Fix more tests
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#88 Improve code quality for GitHub CI
  src/test/data/JsonSerializableAddressBookTest/typicalInternshipsAddressBook.json
Labels: type.Bug

#94 Fix DateValidator bug
  src/main/java/seedu/address/logic/validator/DateValidator.java
Labels: type.Bug, priority.High

#97 Update UserGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.High

#100 Add InternshipApplication tests
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/model/internshipapplication/Email.java
  src/main/java/seedu/address/model/internshipapplication/Name.java
  src/main/java/seedu/address/model/internshipapplication/Role.java
  src/test/java/seedu/address/model/internshipapplication/InternshipApplicationTest.java
  src/test/java/seedu/address/testutil/InternshipApplicationBuilder.java
Labels: type.Task, priority.High

#90 Fix raw types and javadocs
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/InternshipCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/internshipapplication/CompanyTest.java
  src/test/java/seedu/address/model/internshipapplication/InternshipApplicationTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High

#101 Update user guide with new release link
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/choaticman 2.jpg
  docs/images/helpMessage.png
  src/main/java/seedu/hireme/ui/HelpWindow.java
Labels: priority.High

#103 Update user guide
  docs/UserGuide.md
Labels: priority.Medium, severity.Low

#105 Add status feature
  src/main/java/seedu/hireme/logic/validator/NameValidator.java
  src/main/java/seedu/hireme/logic/validator/StatusValidator.java
  src/main/java/seedu/hireme/model/internshipapplication/InternshipApplication.java
  src/main/java/seedu/hireme/model/internshipapplication/Status.java
  src/main/java/seedu/hireme/storage/JsonAdaptedInternship.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidInternshipAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalInternshipsAddressBook.json
  src/test/java/seedu/hireme/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/hireme/testutil/InternshipApplicationBuilder.java
Labels: priority.High

#112 Update tests for storage and parser
  src/main/java/seedu/hireme/storage/JsonAddressBookStorage.java
  src/test/java/seedu/hireme/logic/LogicManagerTest.java
  src/test/java/seedu/hireme/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/hireme/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/hireme/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/hireme/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/hireme/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/hireme/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/hireme/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/hireme/storage/StorageManagerTest.java
Labels: priority.Medium

#117 Add StatusComand and relevent test cases
  src/main/java/seedu/hireme/logic/commands/StatusCommand.java
  src/main/java/seedu/hireme/logic/parser/AddressBookParser.java
  src/main/java/seedu/hireme/logic/parser/StatusCommandParser.java
  src/main/java/seedu/hireme/model/ModelManager.java
  src/main/java/seedu/hireme/model/internshipapplication/InternshipApplication.java
  src/test/java/seedu/hireme/logic/commands/StatusCommandTest.java
  src/test/java/seedu/hireme/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/hireme/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/hireme/logic/parser/StatusCommandParserTest.java
  src/test/java/seedu/hireme/model/AddressBookTest.java
  src/test/java/seedu/hireme/model/internshipapplication/InternshipApplicationTest.java
  src/test/java/seedu/hireme/testutil/InternshipApplicationBuilder.java
  src/test/java/seedu/hireme/testutil/TypicalInternshipApplications.java
Labels: priority.High

#123 Update UML Diagram
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/NewDiagram.puml
Labels: priority.High

#125 Add more logging
  src/main/java/seedu/hireme/model/ModelManager.java
  src/main/java/seedu/hireme/storage/StorageManager.java
  src/test/java/seedu/hireme/storage/StorageManagerTest.java
Labels: priority.High

#120 Update DG and UML
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: priority.Medium

#115 Update tests for commons and commands
  build.gradle
  src/main/java/seedu/hireme/commons/core/Config.java
  src/main/java/seedu/hireme/commons/core/GuiSettings.java
  src/main/java/seedu/hireme/commons/core/LogsCenter.java
  src/main/java/seedu/hireme/commons/util/ConfigUtil.java
  src/main/java/seedu/hireme/commons/util/FileUtil.java
  src/main/java/seedu/hireme/model/internshipapplication/Email.java
  src/test/java/seedu/hireme/commons/core/ConfigTest.java
  src/test/java/seedu/hireme/commons/core/GuiSettingsTest.java
  src/test/java/seedu/hireme/commons/core/VersionTest.java
  src/test/java/seedu/hireme/commons/core/index/IndexTest.java
  src/test/java/seedu/hireme/commons/util/AppUtilTest.java
  src/test/java/seedu/hireme/commons/util/CollectionUtilTest.java
  src/test/java/seedu/hireme/commons/util/ConfigUtilTest.java
  src/test/java/seedu/hireme/commons/util/FileUtilTest.java
  src/test/java/seedu/hireme/commons/util/JsonUtilTest.java
  src/test/java/seedu/hireme/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/hireme/logic/commands/AddCommandTest.java
  src/test/java/seedu/hireme/logic/commands/ClearCommandTest.java
  src/test/java/seedu/hireme/logic/commands/CommandResultTest.java
  src/test/java/seedu/hireme/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/hireme/logic/commands/FindCommandTest.java
  src/test/java/seedu/hireme/logic/commands/ListCommandTest.java
Labels: priority.High

#129 Update Architecture and Find's Implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/team/choaticman 2.md
  docs/team/choaticman.md
Labels: priority.High

#126 Update UML and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: priority.Medium

#110 Add filter by status feature
  build.gradle
  src/main/java/seedu/hireme/logic/commands/FilterCommand.java
  src/main/java/seedu/hireme/logic/parser/AddressBookParser.java
  src/main/java/seedu/hireme/logic/parser/FilterCommandParser.java
  src/main/java/seedu/hireme/logic/parser/ParserUtil.java
  src/main/java/seedu/hireme/logic/validator/StatusValidator.java
  src/main/java/seedu/hireme/model/internshipapplication/StatusPredicate.java
  src/main/java/seedu/hireme/ui/InternshipListPanel.java
  src/test/java/seedu/hireme/logic/commands/FilterCommandTest.java
  src/test/java/seedu/hireme/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/hireme/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/hireme/logic/parser/ParserUtilTest.java
  src/test/java/seedu/hireme/model/internshipapplication/StatusPredicateTest.java
Labels: priority.High

#118 Add sort by date feature
  build.gradle
  src/main/java/seedu/hireme/logic/Messages.java
  src/main/java/seedu/hireme/logic/commands/SortCommand.java
  src/main/java/seedu/hireme/logic/parser/AddressBookParser.java
  src/main/java/seedu/hireme/logic/parser/ParserUtil.java
  src/main/java/seedu/hireme/logic/parser/SortCommandParser.java
  src/main/java/seedu/hireme/logic/validator/DateValidator.java
  src/main/java/seedu/hireme/model/AddressBook.java
  src/main/java/seedu/hireme/model/Model.java
  src/main/java/seedu/hireme/model/ModelManager.java
  src/main/java/seedu/hireme/model/internshipapplication/Date.java
  src/main/java/seedu/hireme/model/internshipapplication/DateComparator.java
  src/main/java/seedu/hireme/model/internshipapplication/UniqueList.java
  src/test/data/JsonSerializableAddressBookTest/typicalInternshipsAddressBook.json
  src/test/java/seedu/hireme/logic/commands/AddCommandTest.java
  src/test/java/seedu/hireme/logic/commands/CommandTestUtil.java
  src/test/java/seedu/hireme/logic/commands/SortCommandTest.java
  src/test/java/seedu/hireme/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/hireme/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/hireme/logic/parser/ParserUtilTest.java
  src/test/java/seedu/hireme/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/hireme/model/internshipapplication/DateComparatorTest.java
  src/test/java/seedu/hireme/model/internshipapplication/DateTest.java
  src/test/java/seedu/hireme/model/internshipapplication/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/hireme/model/internshipapplication/RoleTest.java
  src/test/java/seedu/hireme/testutil/TypicalInternshipApplications.java
Labels: type.Story, priority.High

#132 Update ui uml diagram
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/hireme/ui/InternshipApplicationCard.java
  src/main/java/seedu/hireme/ui/InternshipApplicationListPanel.java
  src/main/java/seedu/hireme/ui/InternshipListPanel.java
  src/main/java/seedu/hireme/ui/MainWindow.java
  src/main/resources/view/InternshipApplicationListCard.fxml
  src/main/resources/view/InternshipApplicationListPanel.fxml
Labels: priority.High

#135 Add ui to show statuses
  src/main/java/seedu/hireme/ui/InternshipApplicationCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InternshipApplicationListCard.fxml
Labels: priority.High

#141 Fix UI bugs regarding Status and Date
  src/main/java/seedu/hireme/logic/commands/StatusCommand.java
  src/main/java/seedu/hireme/logic/parser/ParserUtil.java
  src/main/java/seedu/hireme/logic/validator/DateValidator.java
  src/main/java/seedu/hireme/model/internshipapplication/Date.java
  src/main/resources/view/InternshipApplicationListCard.fxml
Labels: type.Bug, priority.High, severity.High, alpha-bug

#175 Fix insights bugs
  src/main/java/seedu/hireme/commons/util/StringUtil.java
  src/main/java/seedu/hireme/logic/parser/SortCommandParser.java
  src/main/java/seedu/hireme/logic/validator/EmailValidator.java
  src/main/java/seedu/hireme/logic/validator/NameValidator.java
  src/main/java/seedu/hireme/logic/validator/RoleValidator.java
  src/main/java/seedu/hireme/logic/validator/StatusValidator.java
  src/main/java/seedu/hireme/ui/InsightsWindow.java
  src/main/resources/view/InsightsWindow.css
  src/test/java/seedu/hireme/commons/util/StringUtilTest.java
Labels: type.Enhancement, type.Bug, alpha-bug

#180 Update user guide
  docs/UserGuide.md
Labels: type.Task, priority.High

#184 Update DG with model class diagram and status command sequence diagram
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/NewDiagram.puml
  docs/diagrams/StatusSequenceDiagram.puml
  docs/diagrams/style.puml
Labels: priority.High, alpha-bug

#178 Fix inconsistent error message
  src/main/java/seedu/hireme/logic/Messages.java
  src/main/java/seedu/hireme/logic/commands/DeleteCommand.java
  src/main/java/seedu/hireme/logic/commands/StatusCommand.java
  src/main/java/seedu/hireme/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/hireme/commons/util/StringUtilTest.java
  src/test/java/seedu/hireme/logic/LogicManagerTest.java
  src/test/java/seedu/hireme/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/hireme/logic/commands/StatusCommandTest.java
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#183 Update uml and tests
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ChartSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  src/test/java/seedu/hireme/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/hireme/logic/parser/FilterCommandParserTest.java
Labels: priority.Medium

#185 Fix alpha bugs and improve UI
  docs/UserGuide.md
  main - Shortcut.lnk
  src/main/java/seedu/hireme/ui/InternshipApplicationCard.java
  src/main/resources - Shortcut.lnk
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HireMeTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, severity.Medium, alpha-bug

#186 Update user and developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/findAlexDavidResult.png
  docs/images/johndoe.png
Labels: type.Task, priority.Medium, severity.Medium

#181 Add tests for model and fix delete bug
  src/main/java/seedu/hireme/logic/commands/StatusCommand.java
  src/main/java/seedu/hireme/logic/parser/FilterCommandParser.java
  src/main/java/seedu/hireme/logic/validator/RoleValidator.java
  src/main/java/seedu/hireme/logic/validator/StatusValidator.java
  src/main/java/seedu/hireme/model/AddressBook.java
  src/main/java/seedu/hireme/model/internshipapplication/Company.java
  src/main/java/seedu/hireme/model/internshipapplication/Date.java
  src/main/java/seedu/hireme/model/internshipapplication/Email.java
  src/main/java/seedu/hireme/model/internshipapplication/InternshipApplication.java
  src/main/java/seedu/hireme/model/internshipapplication/Name.java
  src/main/java/seedu/hireme/model/internshipapplication/Role.java
  src/main/java/seedu/hireme/model/internshipapplication/Status.java
  src/main/java/seedu/hireme/model/internshipapplication/StatusPredicate.java
  src/main/java/seedu/hireme/model/internshipapplication/UniqueList.java
  src/main/java/seedu/hireme/storage/JsonAdaptedInternship.java
  src/main/java/seedu/hireme/ui/InternshipApplicationCard.java
  src/test/data/JsonSerializableAddressBookTest/typicalInternshipsAddressBook.json
  src/test/java/seedu/hireme/logic/commands/CommandTestUtil.java
  src/test/java/seedu/hireme/logic/commands/FilterCommandTest.java
  src/test/java/seedu/hireme/logic/commands/FindCommandTest.java
  src/test/java/seedu/hireme/logic/commands/SortCommandTest.java
  src/test/java/seedu/hireme/logic/commands/StatusCommandTest.java
  src/test/java/seedu/hireme/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/hireme/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/hireme/logic/parser/ParserUtilTest.java
  src/test/java/seedu/hireme/logic/validator/DateValidatorTest.java
  src/test/java/seedu/hireme/logic/validator/EmailValidatorTest.java
  src/test/java/seedu/hireme/logic/validator/NameValidatorTest.java
  src/test/java/seedu/hireme/logic/validator/RoleValidatorTest.java
  src/test/java/seedu/hireme/logic/validator/StatusValidatorTest.java
  src/test/java/seedu/hireme/model/ModelManagerTest.java
  src/test/java/seedu/hireme/model/internshipapplication/CompanyTest.java
  src/test/java/seedu/hireme/model/internshipapplication/DateTest.java
  src/test/java/seedu/hireme/model/internshipapplication/EmailTest.java
  src/test/java/seedu/hireme/model/internshipapplication/InternshipApplicationTest.java
  src/test/java/seedu/hireme/model/internshipapplication/NameTest.java
  src/test/java/seedu/hireme/model/internshipapplication/RoleTest.java
  src/test/java/seedu/hireme/model/internshipapplication/StatusPredicateTest.java
  src/test/java/seedu/hireme/model/internshipapplication/UniqueListTest.java
  src/test/java/seedu/hireme/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/hireme/testutil/AddressBookBuilder.java
  src/test/java/seedu/hireme/testutil/InternshipApplicationBuilder.java
  src/test/java/seedu/hireme/testutil/InternshipApplicationUtil.java
  src/test/java/seedu/hireme/testutil/SerializableTestClass.java
  src/test/java/seedu/hireme/testutil/TestUtil.java
  src/test/java/seedu/hireme/testutil/TypicalIndexes.java
  src/test/java/seedu/hireme/testutil/TypicalInternshipApplications.java
  src/test/java/seedu/hireme/ui/TestFxmlObject.java
Labels: type.Task, priority.Medium, severity.Medium, alpha-bug
