Repository AY2425S1-CS2103T-W09-3/tp, pull requests merged in 2024-11, with the labels that each got.

#189 Fix UG bugs
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/Ui.png
  docs/images/helpMessage.png
  docs/team/choaticman.md
Labels: priority.High, alpha-bug

#188 Change all commands to full form
  src/main/java/seedu/hireme/logic/commands/AddCommand.java
  src/main/java/seedu/hireme/logic/commands/DeleteCommand.java
  src/main/java/seedu/hireme/logic/commands/FindCommand.java
  src/main/java/seedu/hireme/logic/commands/StatusCommand.java
  src/main/java/seedu/hireme/logic/parser/ParserUtil.java
  src/main/java/seedu/hireme/logic/validator/StatusValidator.java
  src/main/java/seedu/hireme/model/internshipapplication/Status.java
  src/main/java/seedu/hireme/storage/JsonAdaptedInternship.java
  src/test/java/seedu/hireme/logic/LogicManagerTest.java
  src/test/java/seedu/hireme/logic/parser/ParserUtilTest.java
  src/test/java/seedu/hireme/testutil/InternshipApplicationBuilder.java
Labels: priority.High, alpha-bug

#192 Update docs, defensive programming and logs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/piechart.png
  src/main/java/seedu/hireme/logic/commands/AddCommand.java
  src/main/java/seedu/hireme/logic/commands/CommandResult.java
  src/main/java/seedu/hireme/logic/commands/DeleteCommand.java
  src/main/java/seedu/hireme/logic/commands/FilterCommand.java
  src/main/java/seedu/hireme/logic/commands/FindCommand.java
  src/main/java/seedu/hireme/logic/commands/StatusCommand.java
  src/main/java/seedu/hireme/logic/parser/AddCommandParser.java
  src/main/java/seedu/hireme/logic/parser/FilterCommandParser.java
  src/main/java/seedu/hireme/logic/parser/FindCommandParser.java
  src/main/java/seedu/hireme/logic/parser/ParserUtil.java
  src/main/java/seedu/hireme/logic/parser/Prefix.java
  src/main/java/seedu/hireme/logic/parser/SortCommandParser.java
  src/main/java/seedu/hireme/logic/parser/StatusCommandParser.java
  src/main/java/seedu/hireme/logic/validator/EmailValidator.java
  src/main/java/seedu/hireme/logic/validator/NameValidator.java
  src/main/java/seedu/hireme/logic/validator/RoleValidator.java
  src/main/java/seedu/hireme/logic/validator/StatusValidator.java
  src/test/java/seedu/hireme/logic/validator/EmailValidatorTest.java
  src/test/java/seedu/hireme/logic/validator/NameValidatorTest.java
  src/test/java/seedu/hireme/logic/validator/RoleValidatorTest.java
  src/test/java/seedu/hireme/logic/validator/StatusValidatorTest.java
Labels: priority.Medium

#196 Branch dylan update ug
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#194 Update developer guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium, severity.Medium

#193 Add logging and defensive checks
  src/main/java/seedu/hireme/MainApp.java
  src/main/java/seedu/hireme/logic/validator/NameValidator.java
  src/main/java/seedu/hireme/logic/validator/RoleValidator.java
  src/main/java/seedu/hireme/model/AddressBook.java
  src/main/java/seedu/hireme/model/ModelManager.java
  src/main/java/seedu/hireme/model/UserPrefs.java
  src/main/java/seedu/hireme/model/internshipapplication/Company.java
  src/main/java/seedu/hireme/model/internshipapplication/Date.java
  src/main/java/seedu/hireme/model/internshipapplication/DateComparator.java
  src/main/java/seedu/hireme/model/internshipapplication/Email.java
  src/main/java/seedu/hireme/model/internshipapplication/Name.java
  src/main/java/seedu/hireme/model/internshipapplication/Role.java
  src/main/java/seedu/hireme/model/internshipapplication/UniqueList.java
  src/main/java/seedu/hireme/model/internshipapplication/exceptions/DuplicateInternshipApplicationException.java
  src/main/java/seedu/hireme/model/internshipapplication/exceptions/DuplicateInternshipException.java
  src/main/java/seedu/hireme/model/internshipapplication/exceptions/InternshipApplicationNotFoundException.java
  src/main/java/seedu/hireme/model/internshipapplication/exceptions/InternshipNotFoundException.java
  src/main/java/seedu/hireme/model/util/SampleDataUtil.java
  src/main/java/seedu/hireme/storage/JsonAdaptedInternship.java
  src/main/java/seedu/hireme/storage/JsonAddressBookStorage.java
  src/main/java/seedu/hireme/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/hireme/storage/JsonUserPrefsStorage.java
  src/test/java/seedu/hireme/model/AddressBookTest.java
  src/test/java/seedu/hireme/model/internshipapplication/UniqueListTest.java
  src/test/java/seedu/hireme/model/internshipapplication/util/SampleDataUtilTest.java
Labels: type.Task, priority.Medium, severity.Medium

#197 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/HelpSequenceDiagram.puml
Labels: type.Task, priority.Medium, severity.Low

#200 Update UG with introduction
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/Testing.md
  docs/UserGuide.md
  docs/diagrams/FilterSequenceDiagram.puml
  src/main/resources/view/HireMeTheme.css
Labels: priority.Medium

#201 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
Labels: severity.High, alpha-bug

#204 Update Docs
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/DeleteSequenceDiagram-0.png
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StatusActivityDiagram.puml
  docs/diagrams/StatusSequenceDiagram.puml
Labels: priority.Medium

#202 Update error msg
  src/main/java/seedu/hireme/logic/commands/AddCommand.java
  src/main/java/seedu/hireme/model/internshipapplication/Role.java
Labels: priority.High, alpha-bug

#211 Fix UI bugs and update DG
  docs/DeveloperGuide.md
  src/main/resources/view/Extensions.css
  src/main/resources/view/HireMeTheme.css
Labels: priority.Medium

#212 Clear to update chart
  src/main/java/seedu/hireme/logic/commands/ClearCommand.java
  src/test/java/seedu/hireme/logic/commands/ClearCommandTest.java
Labels: priority.High

#214 Update about me
  docs/team/raghava-chittidi.md
  docs/team/zwezeya.md
Labels: type.Task, priority.Low, severity.VeryLow

#208 Branch docs
  README.md
  docs/DeveloperGuide.md
  docs/index.md
Labels: priority.Medium

#217 Fix chart bug
  docs/images/piechart.png
  src/main/java/seedu/hireme/ui/ChartWindow.java
  src/main/resources/view/ChartWindow.fxml
Labels: priority.High

#215 Update error message
  src/main/java/seedu/hireme/logic/commands/StatusCommand.java
Labels: priority.Medium

#219 Fix UG ToC
  docs/UserGuide.md
Labels: alpha-bug

#222 Add hireme logo
  docs/diagrams/FilterSequenceDiagram.puml
  docs/team/xueting.md
  src/main/java/seedu/hireme/ui/UiManager.java
  src/main/resources/images/hireme_logo.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/hireme/commons/util/AppUtilTest.java
Labels: type.Task, priority.Low

#223 Add comprehensive test cases and improve javadocs
  docs/diagrams/StatusActivityDiagram.puml
  src/main/java/seedu/hireme/logic/commands/StatusCommand.java
  src/main/java/seedu/hireme/logic/parser/StatusCommandParser.java
  src/main/java/seedu/hireme/model/internshipapplication/Company.java
  src/main/java/seedu/hireme/model/internshipapplication/Date.java
  src/main/java/seedu/hireme/model/internshipapplication/Email.java
  src/main/java/seedu/hireme/model/internshipapplication/InternshipApplication.java
  src/main/java/seedu/hireme/model/internshipapplication/Name.java
  src/main/java/seedu/hireme/model/internshipapplication/Role.java
  src/main/java/seedu/hireme/model/internshipapplication/Status.java
  src/test/java/seedu/hireme/model/ModelManagerTest.java
  src/test/java/seedu/hireme/model/internshipapplication/CompanyTest.java
  src/test/java/seedu/hireme/model/internshipapplication/DateComparatorTest.java
  src/test/java/seedu/hireme/model/internshipapplication/DateTest.java
  src/test/java/seedu/hireme/model/internshipapplication/EmailTest.java
  src/test/java/seedu/hireme/model/internshipapplication/InternshipApplicationTest.java
  src/test/java/seedu/hireme/model/internshipapplication/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/hireme/model/internshipapplication/NameTest.java
  src/test/java/seedu/hireme/model/internshipapplication/RoleTest.java
Labels: priority.Medium

#225 Fix about us xueting md
  docs/team/xueting.md
Labels: severity.Low

#229 Update docs and readme
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.Medium

#230 Update about us page
  docs/AboutUs.md
  docs/team/choaticman.md
Labels: alpha-bug

#231 Reformat manual testing section
  docs/DeveloperGuide.md
Labels: alpha-bug

#228 Update UI with prompt text
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/xueting.md
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HireMeTheme.css
Labels: severity.Low

#232 Fix bug in docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ExitSequenceDiagram.puml
Labels: type.Task, priority.Medium, severity.Low

#233 Add clear sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/ClearSequenceDiagram.puml
Labels: priority.Medium

#234 Update version to v1.5
  src/main/java/seedu/hireme/MainApp.java
Labels: type.Task

#235 Fix bug in docs
  docs/DeveloperGuide.md
  docs/images/Ui.png
Labels: type.Task, priority.Medium, severity.Low

#314 Add welcome message in UG
  docs/UserGuide.md
Labels: priority.Medium

#315 Add images and overview
  docs/UserGuide.md
  docs/images/accept-status-after.png
  docs/images/accept-status-before.png
  docs/images/add-after.png
  docs/images/add-before.png
  docs/images/delete-after.png
  docs/images/delete-before.png
  docs/images/filter-after.png
  docs/images/filter-before.png
  docs/images/find-after.png
  docs/images/find-before.png
  docs/images/sort-after.png
  docs/images/sort-before.png
Labels: type.Task, priority.Medium, severity.Medium

#316 Fix v1.6 bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindSequenceDiagram.puml
Labels: type.Bug

#318 Doc bugs from PE-D
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ExitSequenceDiagram.puml
Labels: priority.Medium

#317 Fix images and sitemap
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: type.Task, priority.Medium, severity.Medium

#322 Fix UG and DG bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StatusActivityDiagram.puml
Labels: type.Bug, priority.Medium

#321 Update UG Windows Setting up
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterSequenceDiagram.puml
  docs/images/DownloadHireMe.png
  docs/images/HireMeJar.png
  docs/images/LabelledUi.png
  docs/images/OpenWindowsTerminal.png
  docs/images/Ui.png
  docs/images/UndoSequenceDiagram-Logic.png
  docs/images/UndoSequenceDiagram-Model.png
  docs/images/WindowsTerminal.png
  docs/images/Windowscd.png
  docs/images/Windowsfilepath.png
  docs/images/hireme_logo.png
  docs/index.md
  docs/site.json
Labels: type.Bug, priority.Medium

#325 Fix ug and dg bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: type.Task, type.Bug, priority.High

#329 Fix setting up bugs
  docs/UserGuide.md
Labels: type.Bug

#330 Fix ToC and add Glossary to UG
  docs/UserGuide.md
Labels: type.Task

#337 Add spacing between words and images
  docs/UserGuide.md
Labels: priority.Low

#338 Add to glossary
  docs/UserGuide.md
Labels: priority.Low

#339 Fix ug final changes
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: type.Task, priority.Medium, severity.Medium

#340 Add code block
  docs/UserGuide.md
Labels: priority.Low, severity.Low

#343 Fix DG Status Activity Diagram Formatting Issue
  docs/DeveloperGuide.md
  docs/diagrams/StatusActivityDiagram.puml
Labels: severity.Medium

#342 Fix delete error message
  src/main/java/seedu/hireme/logic/commands/DeleteCommand.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/hireme/commons/core/index/IndexTest.java
  src/test/java/seedu/hireme/logic/commands/AddCommandTest.java
  src/test/java/seedu/hireme/logic/commands/CommandTestUtil.java
  src/test/java/seedu/hireme/logic/commands/FindCommandTest.java
  src/test/java/seedu/hireme/model/AddressBookTest.java
  src/test/java/seedu/hireme/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/hireme/testutil/AddressBookBuilder.java
Labels: type.Bug, priority.Medium, severity.Medium

#344 Add points to planned enhancements
  docs/DeveloperGuide.md
Labels: planned enhancement

#347 Add additional formatting
  docs/DeveloperGuide.md
Labels: severity.Medium

#349 Improve error message enhancement
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium, severity.Medium

#351 Add indentation
  docs/DeveloperGuide.md
Labels: priority.Medium

#350 Improve UI planned enhancement
  docs/DeveloperGuide.md
Labels: priority.Low

#355 Add nfrs
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium, severity.Medium
